### ISSUE TITLE
Can't possibly make it find chromedriver

### ISSUE THREAD

**Issue by devingDev** [hardikvasa/google-images-download#110]
Tried on bash for windows AND windows cmd.
always cant find chromedriver.

`chromedriver --version
ChromeDriver 2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb)`

`chromedriver
Starting ChromeDriver 2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb) on port 9515
Only local connections are allowed.`

`googleimagesdownload -cf=cf.json -cd=C:\Users\Kem\AppData\Local\Programs\Python\Python36\Scripts\chromedriver.exe

Item no.: 1 --> Item name = Metal Gear Solid screenshot
Evaluating...
Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine (exception: argument of type 'NoneType' is not iterable)`

**Comment by devingDev** [comment]
Seems like the argument was always "None" for some reason. Hardcoded my path into the python file and it worked. 

Someone should look into why the argument for -cd or --chromedriver is set to None anywway.

**Comment by pandadom** [comment]
same for me :( 

command:
 D:\workspace\dataSets\fotos>googleimagesdownload -cf config.txt --chromedriver="C:\\geckodriver-v0.20.1-win64\\chromedriver.exe"

result:
Evaluating...
Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine (exception: argument of type 'NoneType' is not iterable)

i have also added the folder of the chromedriver to the system PATH but did not change anything

**Comment by devingDev** [comment]
Did you git clone this repo?
If so you should edit the file https://github.com/hardikvasa/google-images-download/blob/master/google_images_download/google_images_download.py 
and hardcode the path like this :  


`        arguments['chromedriver'] = "C:\\geckodriver-v0.20.1-win64\\chromedriver.exe"`

Add it somewhere right before the download function call, I added the line here: 
 https://github.com/hardikvasa/google-images-download/blob/master/google_images_download/google_images_download.py#L813

**Comment by devingDev** [comment]
No problem. If I would understand python more I would try to do a PR but no idea ^^

Have fun

**Comment by hardikvasa** [comment]
Hi @devingDev thanks for the info.

I am assuming the reason it did not work for you is because you are using the combination of config file and command line arguments. When config file argument is provided, all the command line arguments are ignored. I would recommend using the 'chromedriver' argument inside of the config file and then try.

**Comment by hardikvasa** [comment]
I guess it would be worth mentioning the workaround in the doc for folks who would experience a similar behavior. Thanks!

**Comment by hardikvasa** [comment]
Updated the docs...resolving this issue. Thanks.

**Comment by afcruzs** [comment]
Hi @hardikvasa thank you for this awesome library. A suggestion: I was a bit confused about how to use the `chromedriver` argument in the json config, it turns out it needs to be set on each record. I think is reasonable to use the same chromedriver path for all the records instead of duplicating the argument on each record. Going a bit further I identified a list of arguments that could be 'global' for all the records (it would either override the individual arguments per record or throw an error).

If it sounds ok to you I could raise a PR for that. It would be something like

```
{
    "chromedriver: "<thepath>",
     "Records": [...]
}
```

As opposed to:

```
{
     "Records": [
           { 
                   keywords":"class 1",
                   "chromedriver: "<thepath>"
                    .....
           },
           { 
                   keywords":"class 2",
                   "chromedriver: "<thepath>"
                    .....
           }
           ....
      ]

}
```

The list of arguments I think should be "global":

- chromedriver
- usage_rights
- exact_size
- aspect_ratio
- type
- specific_site
- print_paths
- safe_search
- language

**Comment by hardikvasa** [comment]
@afcruzs thanks. that makes sense to make chromedriver param global at the very least. can you please open another issue so we can track this feature request?

**Comment by afcruzs** [comment]
Done @hardikvasa https://github.com/hardikvasa/google-images-download/issues/192#issue-385133610
