### ISSUE TITLE
offset option doesn't work

### ISSUE THREAD

**Issue by ThomasBourgeois** [hardikvasa/google-images-download#180]
I just tried the offest option with following : 
--of 100 --limit 100
to get the next 100 pics. (I can't install chromedriver on my machine to directly get the first 200)

I get the following result : only one image is downloaded. 
I think the program skips exactly the ones he wants to download.
I get the same kind of weird behaviour with --of 50 -- limit 100 : the program only downloads 51 to 100. Not 51 to 151..

Thanks, 
great extension !

**Comment by newgren** [comment]
I have the same issue. Great extension so far otherwise.

**Comment by hardikvasa** [comment]
@ThomasBourgeois this is currently the expected behavior. The only way to download more than 100 images is to use chromedriver. Without chromedriver the page would only return 100 URLs and offset would just end on 100. It would however be good to use an API (hosted on a public server) to make these calls on your behalf and return URLs to client for downloading which will not require the use of Chromedriver. However no plans of currently adding such a feature. :)
