### ISSUE TITLE
urllib2 is removed from python3

### ISSUE THREAD

**Issue by SystemErrorWang** [hardikvasa/google-images-download#19]
In this script, the library 'urllib2' is imported directly in the code, which would cause error. I guess using an if structure and import urllib.request if the python version is python3 can solve this problem.

**Comment by rachmadaniHaryono** [comment]
Hi @SystemErrorWang, we made fork on @rytoj for python3 version. Can you try if it meet your requirement?

**Comment by dennistouchet** [comment]
Replace this code:
`        from urllib2 import Request,urlopen`
`        from urllib2 import URLError, HTTPError`

At lines 139 and 140 to this:

`        version = (3,0)`
`        cur_version = sys.version_info`
`        if cur_version >= version:     #If the Current Version of Python is 3.0 or above`
`            #urllib library for Extracting web pages`
`            from urllib.request import Request, urlopen`
`            from urllib.request import URLError, HTTPError`
`            `
`        else:                          #If the Current Version of Python is 2.x`
`            #urllib library for Extracting web pages`
`            from urllib2 import Request, urlopen`
`            from urllib2 import URLError, HTTPError`

**Comment by ShadabFaiz** [comment]
Since i don't have permission to edit this file,i'm writing it down here.
As of now, this program is not compatible with Python 3.6. 

1.  There are some problems related to syntax. **dennistouchet** has suggested a way to fix it.
2.  Right now, if the directory is already created ,then an exception will be thrown.
Better Approach: is to check is the directory is already created or not.
```
if(os.path.exists(search_keywords)):
print("Directory " + str(search_keywords) + " already exists.")
else:
print("Creating new directory (" + str(search_keywords) + ")")
os.mkdir(search_keywords)
```
3. It can download only 100 images(some are corrupted images).

**Comment by speedious** [comment]
`OSError, e` won't work for python3.5. It should be `OSError as e`.

**Comment by hardikvasa** [comment]
sorry for the delay...the bugs mentioned on this page has been resolved. Thanks everyone for your contributions.
