### ISSUE TITLE
Adding preview for images before downloading them

### ISSUE THREAD

**Issue by jithinlalk25** [hardikvasa/google-images-download#247]
Presently, when the script is run, the images are directly downloaded. It would be more convenient if the users could get a preview of the images before they download all of them. I would like to implement this feature. The users can be provided with a preview of all the images in a webpage. Users can confirm the download after previewing them.

**Comment by ablacklama** [comment]
I think the usefulness of the library really relies on it's ability to download without user input. And it's much faster to download all, then quickly arrow through all the pictures and press delete if you don't like them. A GUI would also make the library significantly heavier. I understand people may have slow internet, or not want to use as much data. But at that point, you should probably just be looking through google images and downloading them by hand, since it won't take much longer anyways.

**Comment by jithinlalk25** [comment]
Hi ablacklama, thanks for your comment. 
> I think the usefulness of the library really relies on it's ability to download without user input. And it's much faster to download all, then quickly arrow through all the pictures and press delete if you don't like them.

I think to implement this as an **optional feature**. Users can also **set the number of images to be viewed**. For example, if a user wants to download 500 images, he can just view 50 or any number of images less than 500 before download. So that he will get a model or type of images that is going to be downloaded. 
So I think this will be more comfortable than deleting all images after download.

> A GUI would also make the library significantly heavier. 

It won't make the library heavier. Because I am adding only a one page HTML file to the library. Users can see the preview on the browser.



> But at that point, you should probably just be looking through google images and downloading them by hand, since it won't take much longer anyways.

For large number of images, this is not practical.

**Comment by ablacklama** [comment]
good points, I think as long as it's lightweight that would be neat. Personally i don't think that helps that much, because you can get an overview of what images you'll be downloading by just googling it; and you won't be able to see the outliers without viewing all the images. But i don't think there's any harm in it.

**Comment by jithinlalk25** [comment]
I thought of giving an overview of the images without any outliers. That is showing them the exact images that are going to be downloaded. 
And it also removes the extra work of gooling images with a lot of filters. 
And as you said it's not a big change. But I think it will be useful for some users like me.

**Comment by whatneuron** [comment]
@jithinlalk25 I am working on something similiar, send me your contact details if you want to work together. Thanks
