### ISSUE TITLE
'0 is all we got for the search filter' 

### ISSUE THREAD

**Issue by jap101** [hardikvasa/google-images-download#316]
I have seen this issue before and am not sure why i am getting it now but i understand that the problem is in the '_get_next_item' function and that the html page does not contain 'rg_meta notranslate' so it returns -1 and no links are found for the images. I dont know why this is happening. Any help is appreciated, thanks.

**Comment by JanGieseler** [comment]
Same issue here. Just installed fresh from the gitlab repo and ran the example

```
from google_images_download import google_images_download   #importing the library

response = google_images_download.googleimagesdownload()   #class instantiation

arguments = {"keywords":"Polar bears,baloons,Beaches","limit":20,"print_urls":True}   #creating list of arguments
paths = response.download(arguments)   #passing the arguments to the function
print(paths)   #printing absolute paths of the downloaded images
```

with the result:

Item no.: 1 --> Item name = Polar bears
Evaluating...
Starting Download...


Unfortunately all 20 could not be downloaded because some images were not downloadable. 0 is all we got for this search filter!

Errors: 0


Item no.: 2 --> Item name = baloons
Evaluating...
Starting Download...


Unfortunately all 20 could not be downloaded because some images were not downloadable. 0 is all we got for this search filter!

Errors: 0


Item no.: 3 --> Item name = Beaches
Evaluating...
Starting Download...


Unfortunately all 20 could not be downloaded because some images were not downloadable. 0 is all we got for this search filter!

Errors: 0

({'Polar bears': [], 'baloons': [], 'Beaches': []}, 0)

**Comment by Joeclinton1** [comment]
Have you tried installing this patch #298?

**Comment by dav-ell** [comment]
I can confirm that the patch works. I copy/pasted the contents of `google_images_download.py` from the patch into the file after I cloned the repo (link to raw patch [here](https://raw.githubusercontent.com/hardikvasa/google-images-download/620e7f54ea29631e5e7d8a2b82a16a40932bf42a/google_images_download/google_images_download.py)). Here's the steps I took to fix it:

```
git clone https://github.com/hardikvasa/google-images-download.git
cd google-images-download
# copy/paste from patch into `google_images_download/google_images_download.py`
python setup.py install
```

**Comment by LunguRadu** [comment]
Dav-ell. I can confirm that it worked for me as well. Thank you

**Comment by jap101** [comment]
Dav-ell, thanks man worked for me.

**Comment by mrgloom** [comment]
This works for me:

```
git clone git@github.com:Joeclinton1/google-images-download.git
cd google-images-download
sudo python setup.py install
```


```
from google_images_download import google_images_download
response = google_images_download.googleimagesdownload()
arguments = {"keywords":"Simpsons","limit":100,"print_urls":True}
paths = response.download(arguments)
```

With output:
```
Unfortunately all 100 could not be downloaded because some images were not downloadable. 94 is all we got for this search filter!

Errors: 6
```

Why this still not in master?

**Comment by mathpopo** [comment]
> python setup.py install

i also meet this issue

 googleimagesdownload -k "北极熊" -l 5

Item no.: 1 --> Item name = \u5317\u6781\u718a
Evaluating...
Starting Download...


Unfortunately all 5 could not be downloaded because some images were not downloadable. 0 is all we got for this search filter!

Errors: 0


Everything downloaded!
Total errors: 0
Total time taken: 4.863688230514526 Seconds

**Comment by dasmehdix** [comment]
Solved [here](https://github.com/hardikvasa/google-images-download/issues/354#issuecomment-895971327). Just build that repo.
