### ISSUE TITLE
for windows

### ISSUE THREAD

**Issue by Joggyjagz7** [hardikvasa/google-images-download#50]
For windows the command 
<cd google-images-download && sudo python setup.py install> gives the error <``bash: sudo: coomand not `fine>`

**Comment by rachmadaniHaryono** [comment]
You can also try

```cd google-images-download && pip install --user . ```

That will install the program using pip on your user folder. 

Just make sure you have pip installed

**Comment by stellpdc** [comment]
I am unable to get the keywords_from_file option to work. I get the message "OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\Stell\\Desktop\\CurrentWorkfile\\Data\\Dorman\\GID\\Dorman 00588\r'".

If I specify keywords in the command instead of using the -kf option, it works fine. I've attached both my keyword file and the console output.

Any help would be appreciated!

[keywords.txt](https://github.com/hardikvasa/google-images-download/files/1808390/keywords.txt)
[output.txt](https://github.com/hardikvasa/google-images-download/files/1808391/output.txt)

**Comment by hardikvasa** [comment]
@Joggyjagz7 did it resolve your issue?

I am closing this issue for now. If you have any other queries, feel free to re-open it.
