### ISSUE TITLE
keywords_from_file throws error

### ISSUE THREAD

**Issue by stellpdc** [hardikvasa/google-images-download#51]
I am unable to get the keywords_from_file option to work. I get the message "OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\Users\Stell\Desktop\CurrentWorkfile\Data\Dorman\GID\Dorman 00588\r'".

If I specify keywords in the command instead of using the -kf option, it works fine. I've attached both my keyword file and the console output.

[error.txt](https://github.com/hardikvasa/google-images-download/files/1808515/error.txt)
[output.txt](https://github.com/hardikvasa/google-images-download/files/1808516/output.txt)

**Comment by hardikvasa** [comment]
@stellpdc the bug is in line 93 of the google_images_download.py file where it is not stripping the '\r' character after reading it from the text file.

I will send a fix soon. But if you want to edit on your end, just replace
`search_keyword.append(line.replace('\n', ''))`

with
`search_keyword.append(line.replace('\n', '').replace('\r', ''))`

**Comment by stellpdc** [comment]
That fixed it beautifully! Thank you!
