### ISSUE TITLE
Download more than 100 images

### ISSUE THREAD

**Issue by DreamFlasher** [hardikvasa/google-images-download#53]
Is there any way to download 1000 images?

**Comment by hardikvasa** [comment]
@DreamFlasher this is not possible for now with this repo. You can refer to #7 to get references to repos that allows you to download more than 100 images for a keyword.

However, due to many people requiring this feature, I will implement it by the end of this week. :-)

**Comment by DreamFlasher** [comment]
@hardikvasa Sorry for not checking the already closed issues! Yeah looks like this is a very important feature, so there should be an open ticket for that. Or point out in the documentation that there are other solutions which have that implemented and one should go to them for this feature, if it's a "won't implement".

**Comment by hardikvasa** [comment]
@DreamFlasher this feature has been deployed. Works fine on Windows and Mac. Testing it on Linux now. Gets all the images that are returned by the google image search. 

Closing this issue for now. If you have any issues, feel free to re-open this.

**Comment by golovetska** [comment]
@hardikvasa  Sorry for commenting on closed issue. Did you manage to test this on Linux as well by now? I am trying to download more than 100 images on `ubuntu` and getting all the time the same error message   `Unfortunately all 1000 could not be downloaded because some images were not downloadable. 0 is all we got for this search filter!
Everything downloaded!
Total Errors: 0`
Works fine if limit is <=100

My python version is  `3.6.3`
`Selenium 3.11.0`

**Comment by hardikvasa** [comment]
@golovetska I am still trying to get this work on Linux. The issue that you are facing is because of the GTK. Firefox requires GKT 3 whereas linux has GKT 2 map by default. You can see this if you look into the `geckodriver.log`. This log file will be in the same directory as your geckodriver file.

The error on the geckodriver.log file:
XPCOMGlueLoad error for file /usr/local/firefox/libmozgtk.so:
libgtk-3.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

More information: https://support.mozilla.org/en-US/questions/1121133

I will try to see if chrome webdriver would be a solution for the issue instead of using firefox.

**Comment by n-gregori** [comment]
@hardikvasa i also have the issue on Windows, 
```
Unfortunately all 200 could not be downloaded because some images were not downloadable. 0 is all we got for this search filter!

Everything downloaded!
Total Errors: 0
```

Works fine if limit is <=100

Python 3.6.3
selenium 3.11.0

**Comment by hardikvasa** [comment]
@n-gregori could you please create a new issue? We can then work on that. On windows it is typically because geckodriver was not added to the environment path correctly.

**Comment by freekeys** [comment]
Sorry I've just realised that I've duplicated this issue for Linux as #56 - want me to delete?

**Comment by hardikvasa** [comment]
@golovetska @n-gregori the script is now updated to use chromedriver (with chrome browser) instead of geckodriver (with firefox browser).

I have successfully tested this script on Windows, Mac, Linux CentOS and Ubuntu and works perfectly fine. I could download 750+ images per keyword (everything that google returns).

You can follow the one time installation guide of chromedriver and chrome browser in the troubleshooting section of the documentation. Do let me know if this works for you.
