### ISSUE TITLE
UI Feature Request

### ISSUE THREAD

**Issue by ManosKoutselakis** [hardikvasa/google-images-download#77]
What about making some UI elements on the current version of google-images-download? Is it planned for later versions?

**Comment by knrdl** [comment]
For now I use this script:
```
google_images_download.py -k "$(zenity --entry --text="Enter Search Text" --title="Keywords")" --size "$(zenity --list --title="Select Size" --column="Size" large medium icon ">400*300" ">640*480" ">800*600" ">1024*768" ">2MP" ">4MP" ">6MP" ">8MP" ">10MP" ">12MP" ">15MP" ">20MP" ">40MP" ">70MP")" -o ~/Downloads
```

Don't know if it is an option for you

**Comment by hardikvasa** [comment]
@ManosKoutselakis I really like the idea of having some UI elements, both while creating a query as well as showing the progress of downloads with image previews.

However, I am not sure if this would be feasible since OS like linux would only have command line option (basically this script should be aware of what OS this is run on).

I have added this in my backlog of features. Closing this issue for now. If you would want to try and work on this feature, feel free open a pull request. :)
