### ISSUE TITLE
Issue with the config file argument type of download

### ISSUE THREAD

**Issue by saikishor** [hardikvasa/google-images-download#88]
Hello,

I really appreciate the work you have put into this. It is really amazing. Recently, I came across a bug in your executable. I wanted to download more than 100 images, but then I used the config file to write all my parameters, but then when I tried to run it shows this.

> $ googleimagesdownload -cf images.config --chromedriver ./chromedriver
> Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine

If I mention them one by one on to the commandline then it works.
This works....
> ~/images$ googleimagesdownload -k "coke can" --limit 500 --chromedriver ./chromedriver
> 
> Item no.: 1 --> Item name = coke can
> Evaluating...

and one more thing. 
giving  arguments in a non-definite order doesn't work:

This works:
> $ googleimagesdownload -k "coke can" --size "medium" --limit 500 --chromedriver ./chromedriver

but this doesn't work:

> $ googleimagesdownload -k "coke can" --limit 500 --size "medium" --chromedriver ./chromedrive

**Comment by hardikvasa** [comment]
@saikishor sry for the delay.

Can you give tell me the way you defined your config file? Also what OS are you running this script on?

For the second issue you reported, i will repro it on my end and revert back.

**Comment by saikishor** [comment]
Sorry for the delay!! I ran it on Ubuntu 14.04 and the issue is same also on 16.04.

The config file, that I have used it the one below:
```
{
    "Records": [
        {
            "keywords": "coke",
            "limit": 250,
            "size": "medium"
        },
        {
            "keywords": "fanta",
            "limit": 250,
            "size": "medium"
        },
        {
            "keywords": "pepsi",
            "limit": 250,
            "size": "medium"
        }
    ]
}
```

**Comment by hardikvasa** [comment]
@saikishor thanks for additional info.

For the first issue, i overlooked the query that you provided...my bad. The reason why you are getting an error for the first one is because you are giving a combination of config file and command line arguments. As of now when config file is mentioned, it will discard everything that is mentioned in the command line. **So you will have to give the chromedriver argument from inside of the config file.**

--------

For the second issue, i tried both the commands you mentioned
`googleimagesdownload -k "coke can" --size "medium" --limit 500 --chromedriver ./chromedriver`

and

`googleimagesdownload -k "coke can" --limit 500 --size "medium" --chromedriver ./chromedrive`

but they both gave me the exact same set of images...no difference. Can you elaborate on what is it thats not working from the second command? Is it throwing an error?

**Comment by hardikvasa** [comment]
Closing this for now. Do let me know if this is still an issue.
